# Generated by Django 4.1.7 on 2023-08-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=120)),
                ('workdescription', models.TextField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('workhours', models.CharField(max_length=10)),
            ],
        ),
    ]
